// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeckService is the API the frontend calls. It only reads Claude Code's
 * files; the two bridge methods are the only ones that change one, and only
 * when the user asks.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConfig(): $CancellablePromise<$models.Config> {
    return $Call.ByID(528827994);
}

/**
 * InstallBridge adds the bridge line to the status line script.
 */
export function InstallBridge(): $CancellablePromise<$models.BridgeStatus> {
    return $Call.ByID(2278977322);
}

/**
 * RemoveBridge takes the bridge line out again.
 */
export function RemoveBridge(): $CancellablePromise<$models.BridgeStatus> {
    return $Call.ByID(1338792429);
}

export function ResetConfig(): $CancellablePromise<$models.Config> {
    return $Call.ByID(3140754909);
}

/**
 * SaveConfig validates, stores and applies the configuration.
 */
export function SaveConfig(c: $models.Config): $CancellablePromise<$models.Config> {
    return $Call.ByID(780753119, c);
}

/**
 * Snapshot returns the current data. The menu bar loop refreshes it; a
 * call that finds it older than the refresh interval reads it again.
 */
export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(231460388);
}
