// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Agent is one subagent, read from its own transcript.
 */
export interface Agent {
    "name": string;
    "project": string;
    "contextPct": number;
    "model": string;

    /**
     * tokens x the configured prices
     */
    "costUsd": number;
    "hasCost": boolean;

    /**
     * context size of the last request
     */
    "tokensIn": number;
    "tokensOut": number;
    "durationSec": number;
    "toolCalls": number;

    /**
     * last activity while running
     */
    "finishedAt": number;
    "running": boolean;
}

/**
 * BridgeStatus tells the UI whether live session data can arrive.
 */
export interface BridgeStatus {
    "scriptPath": string;
    "scriptFound": boolean;
    "installed": boolean;

    /**
     * for a manual install
     */
    "line": string;
}

/**
 * Config is the user-editable configuration, stored as JSON in the OS config dir.
 */
export interface Config {
    /**
     * "" means ~/.claude
     */
    "claudeDir": string;

    /**
     * how often the window re-reads the data
     */
    "refreshSeconds": number;

    /**
     * subagent rows to show
     */
    "maxAgents": number;

    /**
     * used % above which a bar turns yellow
     */
    "warnAt": number;

    /**
     * used % above which a bar turns red
     */
    "dangerAt": number;

    /**
     * tokens; only used when the bridge is off
     */
    "contextWindow": number;

    /**
     * "ascii" or "smooth"
     */
    "barStyle": string;

    /**
     * used % at which a rate limit is flagged
     */
    "limitAlertAt": number;
    "alwaysOnTop": boolean;

    /**
     * sessions and limits only, in one tight block
     */
    "compact": boolean;

    /**
     * the ring gauge with the character
     */
    "mascot": boolean;

    /**
     * animations
     */
    "motion": boolean;

    /**
     * ModelLimits shows the per-model weekly limits, such as "Fable this
     * week". It is off unless the user turns it on.
     */
    "modelLimits": boolean;
    "panels": Panels;
    "git": GitOptions;

    /**
     * Prices turn token counts into cost. The first matching row is used.
     */
    "prices": ModelPrice[] | null;
    "pricesVersion": number;
}

/**
 * GitInfo is the repository state of a session's working directory.
 */
export interface GitInfo {
    "repo": string;
    "branch": string;

    /**
     * "" in the main working tree
     */
    "worktree": string;
}

/**
 * GitOptions chooses the git details shown for each session.
 */
export interface GitOptions {
    "show": boolean;
    "repo": boolean;
    "branch": boolean;
    "worktree": boolean;
}

/**
 * Limit is one rate-limit window, e.g. the 5-hour session or the week.
 */
export interface Limit {
    "key": string;
    "label": string;
    "note": string;
    "usedPct": number;

    /**
     * epoch seconds, 0 when unknown
     */
    "resetsAt": number;
}

/**
 * ModelPrice is the price of one model family in USD per million tokens.
 */
export interface ModelPrice {
    /**
     * part of the model id, e.g. "opus"; "*" matches every model
     */
    "match": string;
    "in": number;
    "out": number;
    "cacheWrite": number;
    "cacheRead": number;
}

/**
 * Panels toggles which sections the window shows.
 */
export interface Panels {
    "sessions": boolean;
    "limits": boolean;
    "run": boolean;
    "agents": boolean;
}

/**
 * Run is a /command run from the hooks' run ledger.
 */
export interface Run {
    "command": string;
    "startedAt": number;
    "endedAt": number;
    "done": boolean;
    "agentCount": number;
    "costUsd": number;
}

/**
 * Session is one Claude Code session: the "Model | [bar] %" line.
 */
export interface Session {
    "id": string;

    /**
     * the session name, when Claude Code reports one
     */
    "name": string;
    "model": string;
    "project": string;
    "cwd": string;

    /**
     * null until the first message is sent
     */
    "contextPct": number | null;
    "costUsd": number;

    /**
     * CostEstimated is false when Claude Code reported the cost, and true
     * when this app priced the transcript with the configured prices.
     */
    "costEstimated": boolean;
    "updatedAt": number;
    "live": boolean;

    /**
     * "statusline" is measured by Claude Code. "transcript" is estimated by
     * this app from the transcript when the bridge is off.
     */
    "source": string;
    "git": GitInfo | null;

    /**
     * Run is this session's own /command run.
     */
    "run": Run | null;

    /**
     * Agents are this session's subagents, most recent first.
     */
    "agents": Agent[] | null;
}

/**
 * Snapshot is everything the window shows, read fresh from disk.
 */
export interface Snapshot {
    "generatedAt": number;
    "sessions": Session[] | null;
    "limits": Limit[] | null;

    /**
     * when the limits were last reported
     */
    "limitsAt": number;

    /**
     * why the per-model limits are missing
     */
    "limitsError": string;

    /**
     * newest subagents over all sessions
     */
    "agents": Agent[] | null;
    "bridge": BridgeStatus;
}
